### PR TITLE
Updated Icons to Pixel art

### PR DESCRIPTION
**Pull request by humboldt123**

### CODE REVIEW

**Review by 5HT2 — CHANGES_REQUESTED** [review]
you spelled inviter wrong, in `inivterLarge.png`

**Review by humboldt123 — COMMENTED** [review]
oke

**Review by 5HT2 — COMMENTED** [review]
I'd prefer the banner to be more simple and fit with the rest of the design. Use a background similar to the old oen?

**Comment by humboldt123** [comment]
oke

**Review by 5HT2 — CHANGES_REQUESTED** [review]
Everything is alright except the banner, as per my previous comment. Just change that and I'll merge

**Review by kibibites — CHANGES_REQUESTED** [review]
Change the ブル to 9b90ff

**Comment by humboldt123** [comment]
We need a minecraft screenshot for the banner as per @dominikaaaa's request

**Comment by 5HT2** [comment]
No, read what I said

**Pull request merged**
