### PR TITLE
added myself to capes list

### PR DESCRIPTION
**Pull request by epicfacethe3rd**
i ame a big boye that works vewy hawrd as a janny amd keep de sevwah safee!!!111!!1!
i dewserve a cape!!!!!
pwease let me have cape bewwa ;-;

### CODE REVIEW

**Comment by ghost** [comment]
ye😱😱

**Comment by epicfacethe3rd** [comment]
bewwa?

**Comment by 5HT2** [comment]
mmmm yes good idea

**Comment by 5HT2** [comment]
merge conflicts :(

**Comment by humboldt123** [comment]
I thought you said images should be in kami blue assets for security???

**Comment by 5HT2** [comment]
that too

**Comment by epicfacethe3rd** [comment]
kk, will fix

**Pull request closed without merging**
